<?php
/** @var Cadence\Pinterest\Block\AbstractBlock $block */
$helper = $block->getHelper();
if (!$helper->isConversionPixelEnabled()) {
	return;
}
$id = $helper->getVisitorPixelId();
?>
<?php
/** @var Magento\Sales\Model\Order $order */
$order = $helper->getOrder();

if (!$order) {
	//Failsafe for bad order id
	return;
}

$grand_total = round($order->getGrandTotal(), 2);
$currency_code = $block->getCurrencyCode();
$qtyOrdered = $helper->getOrderItemsQty();
$orderItemJson = $helper->getOrderItemsJson();
?>
<!-- Pinterest Conversion Code for Conversions -->
<script>
    pintrk('track','checkout', {
        value: <?php echo $grand_total ?>,
        currency: '<?php echo $currency_code ?>',
        order_quantity: <?php echo $qtyOrdered; ?>,
        line_items: <?php echo $orderItemJson ?>
    });
</script>
<noscript>
<img height="1" width="1" style="display:none;" alt=""
     src="https://ct.pinterest.com/v3/?tid=<?php echo $id ?>&event=checkout&ed[value]=<?php echo $grand_total ?>&ed[order_quantity]=<?php echo $qtyOrdered
     ?>&ed[currency]=<?php echo $currency_code ?>&noscript=1"/>
</noscript>
